// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGroupings(arg1) {
  return window['go']['app']['App']['GetGroupings'](arg1);
}

export function ListSessions() {
  return window['go']['app']['App']['ListSessions']();
}

export function NewSession(arg1, arg2) {
  return window['go']['app']['App']['NewSession'](arg1, arg2);
}

export function NewSessionData() {
  return window['go']['app']['App']['NewSessionData']();
}

export function OpenFileDialog() {
  return window['go']['app']['App']['OpenFileDialog']();
}

export function SetSession(arg1) {
  return window['go']['app']['App']['SetSession'](arg1);
}
