// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function NewSession() {
  return window['go']['app']['App']['NewSession']();
}

export function SaveSession(arg1) {
  return window['go']['app']['App']['SaveSession'](arg1);
}
