// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {internal} from '../models';

export function GetGroupings(arg1:string):Promise<Array<internal.Grouping>>;

export function ListSessions():Promise<Array<internal.SessionData>>;

export function NewSession(arg1:internal.SessionData,arg2:string):Promise<void>;

export function NewSessionData():Promise<internal.SessionData>;

export function OpenFileDialog():Promise<string>;

export function SetSession(arg1:string):Promise<void>;
