// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {internal} from '../models';

export function CreateSession(arg1:internal.SessionInfo,arg2:string):Promise<string>;

export function DeleteSession(arg1:string):Promise<void>;

export function GetGroupings(arg1:string,arg2:string):Promise<Array<internal.Grouping>>;

export function GetSessionData(arg1:string):Promise<internal.SessionInfo>;

export function ListSessions():Promise<Array<internal.SessionInfo>>;

export function NewSessionData():Promise<internal.SessionInfo>;

export function OpenFileDialog():Promise<string>;

export function SetSessionData(arg1:internal.SessionInfo):Promise<void>;
