// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {internal} from '../models';

export function CreateSession(arg1:internal.SessionInfo,arg2:string):Promise<void>;

export function DeleteSession(arg1:string):Promise<void>;

export function GetGroupings(arg1:string):Promise<Array<internal.Grouping>>;

export function ListSessions():Promise<Array<internal.SessionInfo>>;

export function NewSessionData():Promise<internal.SessionInfo>;

export function OpenFileDialog():Promise<string>;

export function SetSession(arg1:string):Promise<void>;

export function UpdateGrouping(arg1:internal.Grouping):Promise<void>;

export function UpdateSessionData(arg1:internal.SessionInfo):Promise<void>;
