// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBoatIDModel(arg1, arg2) {
  return window['go']['app']['App']['GetBoatIDModel'](arg1, arg2);
}

export function GroupByBoatID() {
  return window['go']['app']['App']['GroupByBoatID']();
}

export function OpenFileDialog() {
  return window['go']['app']['App']['OpenFileDialog']();
}

export function SetSortingMetal(arg1) {
  return window['go']['app']['App']['SetSortingMetal'](arg1);
}
