// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDropArea():Promise<string>;

export function GetModelContent(arg1:number):Promise<string>;

export function GetModels(arg1:string):Promise<string>;

export function OpenFileDialog():Promise<void>;
