// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBoatIDModel(arg1:string,arg2:string):Promise<string>;

export function GroupByBoatID():Promise<string>;

export function OpenFileDialog():Promise<void>;

export function SetSortingMetal(arg1:string):Promise<string>;
