// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetModel(arg1, arg2) {
  return window['go']['app']['ModelInterface']['GetModel'](arg1, arg2);
}

export function GetModels() {
  return window['go']['app']['ModelInterface']['GetModels']();
}
