// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GroupByBoatID() {
  return window['go']['app']['viewModelInterface']['GroupByBoatID']();
}

export function ReadFile() {
  return window['go']['app']['viewModelInterface']['ReadFile']();
}
