// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBoatIDModel(arg1, arg2) {
  return window['go']['app']['ViewModelInterface']['GetBoatIDModel'](arg1, arg2);
}

export function GroupByBoatID() {
  return window['go']['app']['ViewModelInterface']['GroupByBoatID']();
}

export function GroupByOperator() {
  return window['go']['app']['ViewModelInterface']['GroupByOperator']();
}

export function ReadFile() {
  return window['go']['app']['ViewModelInterface']['ReadFile']();
}

export function SetSortingMetal(arg1) {
  return window['go']['app']['ViewModelInterface']['SetSortingMetal'](arg1);
}
