// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GroupByBoatID():Promise<string>;

export function ReadFile():Promise<void>;
