// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {internal} from '../models';

export function GetModels(arg1:string):Promise<Array<internal.Grouping>>;

export function OpenFileDialog():Promise<void>;
